# Test workflow for cache deletion functionality
name: Test Cache Deletion

on:
    push:
        branches:
            - test-cache-deletion
    pull_request:
        branches:
            - test-cache-deletion
    workflow_dispatch:

concurrency:
    group: ${{ github.ref }}-test-cache-deletion
    cancel-in-progress: true

jobs:
    test_cache_deletion:
        name: Test Cache Deletion
        runs-on: ubuntu-latest
        
        container:
            image: ghcr.io/project-chip/chip-build:172
        
        env:
            CCACHE_KEY: test-ccache-${{ github.sha }}
        
        steps:
            - name: Checkout
              uses: actions/checkout@v5
              
            - name: Checkout submodules & Bootstrap
              uses: ./.github/actions/checkout-submodules-and-bootstrap
              with:
                  platform: linux
                  bootstrap-log-name: bootstrap-logs-test
                  
            - name: Setup ccache directory
              run: mkdir -p .ccache
              
            - name: Create dummy cache content
              run: |
                  echo "Test cache content" > .ccache/test.txt
                  echo "Cache size: $(du -sh .ccache)"
                  
            - name: Build single small app (lighting-app)
              env:
                  CCACHE_DIR: "${{ github.workspace }}/.ccache"
              run: |
                  ./scripts/run_in_build_env.sh \
                     "./scripts/build/build_examples.py \
                        --target linux-x64-light-no-ble-no-wifi-no-shell-clang \
                        --pw-command-launcher=ccache \
                        build \
                     "
                  
            - name: Show cache stats
              run: |
                  echo "Final cache size: $(du -sh .ccache)"
                  ls -lah .ccache/ || true
                  
            - name: Delete existing ccache before save
              uses: ./.github/actions/delete-cache
              with:
                  cache-key: ${{ env.CCACHE_KEY }}
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  
            - name: Save ccache
              uses: actions/cache/save@v4
              with:
                  path: .ccache
                  key: ${{ env.CCACHE_KEY }}
                  
            - name: Verify cache was saved
              run: echo "Cache key used - ${{ env.CCACHE_KEY }}"

